version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: .env
    volumes:
      - ./:/app
      - ./vendor/bundle:/usr/local/bundle
    working_dir: /app

  db:
    image: postgres:11.4-alpine
    env_file: .env

networks:
  default:
    external:
      name: localnet
