version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: rails_app
          POSTGRES_PASSWORD: password
    environment:
      POSTGRES_USER: rails_app
      POSTGRES_PASSWORD: password
    working_directory: ~/rails_app
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-app-{{ checksum "Gemfile.lock" }}
            - rails-app
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs 4 --retry 3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: rails-app-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - rails-app-yarn-{{ checksum "yarn.lock" }}
            - rails-app-yarn
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: rails-app-yarn-{{ checksum "yarn.lock" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load --trace
      - run: bundle exec rspec
